//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_frontend.Pages
{


    public partial class nuevoUsuario
    {

        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// litPageSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageSubtitle;

        /// <summary>
        /// vsSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsSummary;

        /// <summary>
        /// pnlForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>
        /// txtNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// rfvNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        /// <summary>
        /// txtApellido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellido;

        /// <summary>
        /// rfvApellido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApellido;

        /// <summary>
        /// ddlRol control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRol;

        /// <summary>
        /// rfvRol control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRol;

        /// <summary>
        /// txtCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>
        /// rfvCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCorreo;

        /// <summary>
        /// revCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCorreo;

        /// <summary>
        /// litPasswordHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPasswordHint;

        /// <summary>
        /// txtContrasena control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContrasena;

        /// <summary>
        /// rfvContrasena control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContrasena;

        /// <summary>
        /// revContrasena control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContrasena;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
