//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_frontend.Pages
{


    public partial class usuarios
    {

        /// <summary>
        /// litTotalUsuarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalUsuarios;

        /// <summary>
        /// litKpiTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litKpiTotal;

        /// <summary>
        /// litKpiActivos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litKpiActivos;

        /// <summary>
        /// litKpiAdministradores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litKpiAdministradores;

        /// <summary>
        /// litKpiNuevosMes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litKpiNuevosMes;

        /// <summary>
        /// litRolOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRolOptions;

        /// <summary>
        /// litEstadoOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEstadoOptions;

        /// <summary>
        /// rptUsuarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsuarios;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// rptUsuariosCard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsuariosCard;

        /// <summary>
        /// hfDeleteId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteId;

        /// <summary>
        /// btnDeleteConfirm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDeleteConfirm;
    }
}
